let obj = {
  "contactinfo": {
  "firstName": "Emily",
  "lastName": "Johnson",
  "email": "emily.johnson@example.com",
  "city": "Seattle",
  "country": "United States",
  "phoneNumber": "+1 (555) 123-4567",
  "linkedIn": "linkedin.com/in/emilyjohnson",
  "summary": "Results-driven software engineer with 7+ years of experience in full-stack development. Passionate about building scalable, efficient systems and mentoring junior developers. Strong problem-solving skills with expertise in cloud technologies and modern web frameworks.",
  },
  aiGeneratedSummaries: [],
  "skills": [
    "JavaScript",
    "React",
    "Node.js",
    "Python",
    "AWS",
    "Docker",
    "SQL",
    "Agile Methodologies"
  ],
  
  "experience": [
    {
      "jobTitle": "Senior Software Engineer",
      "company": "TechSolutions Inc.",
      "startYear": "2018",
      "startMonth": "June",
      "endYear": "",
      "endMonth": "",
      "present": true,
      "description": "Lead development team building scalable web applications using React and Node.js. Implemented CI/CD pipelines reducing deployment time by 40%."
    },
    {
      "jobTitle": "Software Developer",
      "company": "Digital Innovations LLC",
      "startYear": "2015",
      "startMonth": "August",
      "endYear": "2018",
      "endMonth": "May",
      "present": false,
      "description": "Developed and maintained e-commerce platforms. Optimized database queries improving system performance by 25%."
    }
  ],
  "education": [
    {
      "institution": "University of Washington",
      "degree": "Master of Science",
      "graduationMonth": "May",
      "graduationYear": "2015",
      "fieldOfStudy": "Computer Science"
    },
    {
      "institution": "Stanford University",
      "degree": "Bachelor of Science",
      "graduationMonth": "June",
      "graduationYear": "2013",
      "fieldOfStudy": "Software Engineering"
    }
  ],
  "projects": [
    {
      "title": "Task Management App",
      "description": "Developed a full-stack task management application with user authentication and real-time updates.",
      "url": "github.com/emilyj/task-manager"
    },
    {
      "title": "Health Tracker Dashboard",
      "description": "Created a data visualization dashboard for fitness metrics using D3.js and React.",
      "url": "healthtracker.example.com"
    }
  ],
  "certifications": [
    {
      "name": "AWS Certified Solutions Architect",
      "organization": "Amazon Web Services",
      "issueMonth": "November",
      "issueYear": "2020"
    },
    {
      "name": "Google Professional Data Engineer",
      "organization": "Google Cloud",
      "issueMonth": "March",
      "issueYear": "2019"
    },
    
  ],
  "languages": [
    {
      "language": "English",
      "proficiency": "Native",
    },
    {
      "language": "Spanish",
      "proficiency": "Intermediate",
    }
  ],
  
};

let degrees = [
  "Associate in Arts (A.A.)",
  "Associate in Science (A.S.)",
  "Bachelor of Arts (B.A.)",
  "Bachelor of Science (B.S.)",
  "Master of Arts (M.A.)",
  "Master of Science (M.S.)",
  "Master of Business Administration (M.B.A.)",
  "Associate in Fine Arts (A.F.A.)",
  "Associate in Applied Science (A.A.S.)",
  "Certification",
  "Doctor of Information Technology (D.I.T.)",
  "Diploma",
  "Doctor of Architecture (D.Arch.)",
  "Doctor of Arts (D.A.)",
  "Doctor of Arts in Teaching (D.A.T.)",
  "Doctor of Applied Science (D.A.S.)",
  "Doctor of Business Administration (D.B.A.)",
  "Doctor of Canon Law (J.C.D.)",
  "Doctor of Chemistry (D.Chem.)",
  "Doctor of Church Music (D.C.M.)",
  "Doctor of Criminal Justice (D.C.J)",
  "Doctor of Criminology (D.Crim.)",
  "Doctor of Comparative Law (D.Comp.L.)",
  "Doctor of Civil Law (D.C.L.)",
  "Doctor of Design (D.Des.)",
  "Doctor of Education (Ed.D)",
  "Doctor of Engineering (D.Eng.)",
  "Doctor of Environment (D.Env.)",
  "Doctor of Fine Arts (D.F.A.)",
  "Doctor of Forestry (D.F.)",
  "Doctor of Geological Science (D.G.S.)",
  "Doctor of Health Administration (D.H.A.)",
  "Doctor of Health and Safety (D.H.S.)",
  "Doctor of Hebrew Letters (D.H.L.)",
  "Doctor of Hebrew Studies (D.H.S.)",
  "Doctor of Industrial Technology (D.I.T.)",
  "Doctor of Juridical Science (S.J.D.)",
  "Doctor of Library Science (D.L.S.)",
  "Doctor of Medical Science (D.M.Sc.)",
  "Doctor of Ministry (D.Min.)",
  "Doctor of Missiology (D.Miss.)",
  "Doctor of Music (D.M.)",
  "Doctor of Music Education (D.M.E.)",
  "Doctor of Music Ministry (D.M.M.)",
  "Doctor of Musical Arts (D.M.A.)",
  "Doctor of Modern Languages (D.M.L.)",
  "Doctor of Nursing Science (D.N.Sc.)",
  "Doctor of Philosophy (Ph.D.)",
  "Doctor of Physical Education (D.P.E.)",
  "Doctor of Professional Studies (D.P.S.)",
  "Doctor of Public Administration (D.P.A.)",
  "Doctor of Public Health (D.P.H.)",
  "Doctor of Recreation (D.Rec.)",
  "Doctor of Rehabilitation (Rh.D.)",
  "Doctor of Religious Education (D.R.E.)",
  "Doctor of Sacred Music (D.S.M.)",
  "Doctor of Sacred Theology (S.T.D.)",
  "Doctor of Science (D.Sc.)",
  "Doctor of Science and Hygiene (D.Sc.H.)",
  "Doctor of Science in Dentistry (D.Sc.D.)",
  "Doctor of Science in Veterinary Medicine (D.Sc.V.M.)",
  "Doctor of Science of Law (L.Sc.D.)",
  "Doctor of Social Science (D.S.Sc.)",
  "Doctor of Social Work (D.S.W.)",
  "Doctor of Theology (Th.D.)",
  "Doctor of Audiology (Au.D.)",
  "Doctor of Behavioral Health (D.B.H.)",
  "Doctor of Chiropractic Medicine (D.C.)",
  "Doctor of Computer Science (D.C.Sc.)",
  "Doctor of Dental Surgery (D.D.S.)",
  "Doctor of Medical Dentistry (D.M.D.)",
  "Doctor of Health Science (D.H.Sc.)",
  "Juris Doctor (J.D.)",
  "Doctor of Management (D.Mgt.)",
  "Doctor of Medicine (M.D.)",
  "Doctor of Practical Theology (D.P.Th.)",
  "Doctor of Biblical Studies (D.B.S.)",
  "Doctor of Counseling (D.Coun.)",
  "Doctor of Educational Ministry (D.Ed.Min.)",
  "Doctor of Pastoral Music (D.P.M.)",
  "Doctor of Worship Studies (D.W.S.)",
  "Doctor of Naturopathic Medicine (N.D.)",
  "Doctor of Nursing Practice (D.N.P.)",
  "Doctor of Nurse Anesthesia Practice (D.N.A.P.)",
  "Doctor of Occupational Therapy (D.O.T.)",
  "Doctor of Optometry (O.D.)",
  "Doctor of Osteopathic Medicine (D.O.)",
  "Doctor of Pharmacy (Pharm.D.)",
  "Doctor of Physical Therapy (D.P.T.)",
  "Doctor of Podiatric Medicine (D.P.M.)",
  "Doctor of Psychology (D.Psy.)",
  "Doctor of Speech-Language Pathology (D.S.L.P.)",
  "Doctor of Veterinary Medicine (D.V.M.)",
  "High School",
];
