let dummyData = {
  contactInfo: {
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@example.com",
    city: "Toronto",
    country: "Canada",
    phoneNumber: "+1 (416) 987-6543",
    linkedIn: "linkedin.com/in/michaelchen",
  },
  summary:
    "Innovative data scientist with 5+ years of experience in machine learning and big data analytics. Specialized in developing predictive models and data-driven solutions for business challenges. Strong communicator with proven ability to translate complex technical concepts for non-technical stakeholders.",
  aiGeneratedSummaries: [],
  skills: [
    "Python",
    "TensorFlow",
    "PyTorch",
    "SQL",
    "Big Data",
    "Data Visualization",
    "Cloud Computing",
    "Statistical Modeling",
  ],

  experience: [
    {
      jobTitle: "Lead Data Scientist",
      company: "DataInsights Corp.",
      startYear: "2019",
      startMonth: "April",
      endYear: "",
      endMonth: "",
      present: true,
      description:
        "Lead a team developing machine learning models for customer behavior prediction. Implemented new algorithms that improved prediction accuracy by 35%.",
    },
    {
      jobTitle: "Data Analyst",
      company: "Analytics Pro",
      startYear: "2017",
      startMonth: "January",
      endYear: "2019",
      endMonth: "March",
      present: false,
      description:
        "Performed data mining and analysis for client projects. Created automated reporting systems that reduced manual work by 60%.",
    },
  ],
  education: [
    {
      institution: "University of Toronto",
      degree: "Master of Science",
      graduationMonth: "November",
      graduationYear: "2016",
      fieldOfStudy: "Data Science",
    },
    {
      institution: "McGill University",
      degree: "Bachelor of Science",
      graduationMonth: "May",
      graduationYear: "2014",
      fieldOfStudy: "Statistics",
    },
  ],
  projects: [
    {
      title: "Sentiment Analysis Tool",
      description:
        "Built a natural language processing system to analyze customer feedback sentiment across multiple channels.",
      url: "github.com/michaelc/sentiment-analysis",
    },
    {
      title: "Fraud Detection System",
      description:
        "Developed a machine learning model to identify fraudulent transactions with 92% accuracy.",
      url: "github.com/michaelc/fraud-detection",
    },
  ],
  certifications: [
    {
      name: "TensorFlow Developer Certificate",
      organization: "Google",
      issueMonth: "September",
      issueYear: "2021",
    },
    {
      name: "Microsoft Certified: Azure Data Scientist",
      organization: "Microsoft",
      issueMonth: "July",
      issueYear: "2020",
    },
  ],
  languages: [
    {
      language: "English",
      proficiency: "Native",
    },
    {
      language: "Mandarin",
      proficiency: "Fluent",
    },
    {
      language: "French",
      proficiency: "Intermediate",
    },
  ],
};

let emptyData = {
  contactInfo: {
    firstName: "",
    lastName: "",
    email: "",
    city: "",
    country: "",
    phoneNumber: "",
    linkedIn: "",
  },
  summary: "",
  aiGeneratedSummaries: [],
  skills: [],

  experience: [
    {
      jobTitle: "",
      company: "",
      startYear: "",
      startMonth: "",
      endYear: "",
      endMonth: "",
      present: false,
      description: "",
    },
  ],
  education: [
    {
      institution: "",
      degree: "",
      graduationMonth: "",
      graduationYear: "",
      fieldOfStudy: "",
    },
  ],
};

let degrees = [
  "Associate in Arts (A.A.)",
  "Associate in Science (A.S.)",
  "Bachelor of Arts (B.A.)",
  "Bachelor of Science (B.S.)",
  "Master of Arts (M.A.)",
  "Master of Science (M.S.)",
  "Master of Business Administration (M.B.A.)",
  "Associate in Fine Arts (A.F.A.)",
  "Associate in Applied Science (A.A.S.)",
  "Certification",
  "Doctor of Information Technology (D.I.T.)",
  "Diploma",
  "Doctor of Architecture (D.Arch.)",
  "Doctor of Arts (D.A.)",
  "Doctor of Arts in Teaching (D.A.T.)",
  "Doctor of Applied Science (D.A.S.)",
  "Doctor of Business Administration (D.B.A.)",
  "Doctor of Canon Law (J.C.D.)",
  "Doctor of Chemistry (D.Chem.)",
  "Doctor of Church Music (D.C.M.)",
  "Doctor of Criminal Justice (D.C.J)",
  "Doctor of Criminology (D.Crim.)",
  "Doctor of Comparative Law (D.Comp.L.)",
  "Doctor of Civil Law (D.C.L.)",
  "Doctor of Design (D.Des.)",
  "Doctor of Education (Ed.D)",
  "Doctor of Engineering (D.Eng.)",
  "Doctor of Environment (D.Env.)",
  "Doctor of Fine Arts (D.F.A.)",
  "Doctor of Forestry (D.F.)",
  "Doctor of Geological Science (D.G.S.)",
  "Doctor of Health Administration (D.H.A.)",
  "Doctor of Health and Safety (D.H.S.)",
  "Doctor of Hebrew Letters (D.H.L.)",
  "Doctor of Hebrew Studies (D.H.S.)",
  "Doctor of Industrial Technology (D.I.T.)",
  "Doctor of Juridical Science (S.J.D.)",
  "Doctor of Library Science (D.L.S.)",
  "Doctor of Medical Science (D.M.Sc.)",
  "Doctor of Ministry (D.Min.)",
  "Doctor of Missiology (D.Miss.)",
  "Doctor of Music (D.M.)",
  "Doctor of Music Education (D.M.E.)",
  "Doctor of Music Ministry (D.M.M.)",
  "Doctor of Musical Arts (D.M.A.)",
  "Doctor of Modern Languages (D.M.L.)",
  "Doctor of Nursing Science (D.N.Sc.)",
  "Doctor of Philosophy (Ph.D.)",
  "Doctor of Physical Education (D.P.E.)",
  "Doctor of Professional Studies (D.P.S.)",
  "Doctor of Public Administration (D.P.A.)",
  "Doctor of Public Health (D.P.H.)",
  "Doctor of Recreation (D.Rec.)",
  "Doctor of Rehabilitation (Rh.D.)",
  "Doctor of Religious Education (D.R.E.)",
  "Doctor of Sacred Music (D.S.M.)",
  "Doctor of Sacred Theology (S.T.D.)",
  "Doctor of Science (D.Sc.)",
  "Doctor of Science and Hygiene (D.Sc.H.)",
  "Doctor of Science in Dentistry (D.Sc.D.)",
  "Doctor of Science in Veterinary Medicine (D.Sc.V.M.)",
  "Doctor of Science of Law (L.Sc.D.)",
  "Doctor of Social Science (D.S.Sc.)",
  "Doctor of Social Work (D.S.W.)",
  "Doctor of Theology (Th.D.)",
  "Doctor of Audiology (Au.D.)",
  "Doctor of Behavioral Health (D.B.H.)",
  "Doctor of Chiropractic Medicine (D.C.)",
  "Doctor of Computer Science (D.C.Sc.)",
  "Doctor of Dental Surgery (D.D.S.)",
  "Doctor of Medical Dentistry (D.M.D.)",
  "Doctor of Health Science (D.H.Sc.)",
  "Juris Doctor (J.D.)",
  "Doctor of Management (D.Mgt.)",
  "Doctor of Medicine (M.D.)",
  "Doctor of Practical Theology (D.P.Th.)",
  "Doctor of Biblical Studies (D.B.S.)",
  "Doctor of Counseling (D.Coun.)",
  "Doctor of Educational Ministry (D.Ed.Min.)",
  "Doctor of Pastoral Music (D.P.M.)",
  "Doctor of Worship Studies (D.W.S.)",
  "Doctor of Naturopathic Medicine (N.D.)",
  "Doctor of Nursing Practice (D.N.P.)",
  "Doctor of Nurse Anesthesia Practice (D.N.A.P.)",
  "Doctor of Occupational Therapy (D.O.T.)",
  "Doctor of Optometry (O.D.)",
  "Doctor of Osteopathic Medicine (D.O.)",
  "Doctor of Pharmacy (Pharm.D.)",
  "Doctor of Physical Therapy (D.P.T.)",
  "Doctor of Podiatric Medicine (D.P.M.)",
  "Doctor of Psychology (D.Psy.)",
  "Doctor of Speech-Language Pathology (D.S.L.P.)",
  "Doctor of Veterinary Medicine (D.V.M.)",
  "High School",
];
